version: '3'

x-base: &default-config
  restart: unless-stopped
  ulimits:
    nproc: 65535
    nofile:
      soft: 20000
      hard: 40000
  stop_grace_period: 1m
  logging:
    driver: json-file
    options:
      max-size: '100m'
      max-file: '1'
  mem_swappiness: 0


services:
  python_base:
    << : *default-config
    image: python:3.11.9-slim-bookworm
    command: /bin/bash
    volumes:
      - ./data:/data
    tty: true
    