version: "3.9"

x-base: &default-config
  restart: unless-stopped
  ulimits:
    nproc: 65535
    nofile:
      soft: 20000
      hard: 40000
  stop_grace_period: 1m
  logging:
    driver: json-file
    options:
      max-size: '100m'
      max-file: '1'
  mem_swappiness: 0

services:
  derper:
    <<: *default-config
    image: fredliang/derper
    container_name: derper
    ports:
      - '3478:3478/udp'
    environment:
      DERP_ADDR: ":80"
      DERP_VERIFY_CLIENTS: true
    volumes:
      - /var/run/tailscale/tailscaled.sock:/var/run/tailscale/tailscaled.sock

networks:
  default:
    external: true
    name: app
