version: "3.9"

services:
  jupyterhub:
    # image: jupyterhub/jupyterhub:latest
    image: jupyterhub/singleuser:latest
    restart: "unless-stopped"
    container_name: jupyterhub
    ports:
      - 8888:8888
    volumes:
      - ./data/:/home/jovyan/work
